# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# try
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: buildAndReleaseTask@0
  inputs:
    ioServerUrl: 'http://87e992c641da.ngrok.io'
    ioServerToken: 'b331c44c-960b-4bd0-89b9-0604119c5df7'
    workflowServerUrl: 'http://2839eb3c23d1.ngrok.io'
    releaseType: 'major'
    ioManifestUrl: 'https://raw.githubusercontent.com/synopsys-sig/io-artifacts/2021.04/io-manifest.yml'
    additionalWorkflowArgs: '--persona=developer --polaris.url=$(POLARIS_SERVER_URL) --polaris.token=$(POLARIS_ACCESS_TOKEN) --sensitive.package.pattern=''.*(\\+\\+\\+.*(org\\/hdivsamples\\/security)).*'''