# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# try
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# - task: buildAndReleaseTask@0
#   inputs:
#     ioServerUrl: 'http://87e992c641da.ngrok.io'
#     ioServerToken: '$(IO_SERVER_TOKEN)'
#     workflowServerUrl: 'http://2839eb3c23d1.ngrok.io'
#     ioManifestUrl: 'https://raw.githubusercontent.com/synopsys-sig/io-artifacts/2021.04/io-manifest.yml'
#     releaseType: 'major'
#     additionalWorkflowArgs: '--persona=developer --polaris.url=$(POLARIS_SERVER_URL) --polaris.token=$(POLARIS_ACCESS_TOKEN) --sensitive.package.pattern=''.*(\\+\\+\\+.*(org\\/hdivsamples\\/security)).*'''

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      FOO="some value"
      echo "##vso[task.setvariable variable=FOO]$FOO"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
       echo "$(FOO)"
       echo "$FOO"

# - task: buildAndReleaseTask@0
#   inputs:
#     ioServerUrl: 'http://87e992c641da.ngrok.io'
#     ioServerToken: '$(IO_SERVER_TOKEN)'
#     workflowServerUrl: 'http://2839eb3c23d1.ngrok.io'
#     ioManifestUrl: 'https://raw.githubusercontent.com/synopsys-sig/io-artifacts/2021.04/io-manifest.yml'
#     stage: 'WORKFLOW'
#     releaseType: 'major'
#     additionalWorkflowArgs: '--IS_SAST_ENABLED=$(is_sast_enabled) --IS_SCA_ENABLED=$(is_sca_enabled) --polaris.project.name=''sig-devsecops/github-io-sample'' --polaris.url=$(POLARIS_SERVER_URL) --polaris.token=$(POLARIS_ACCESS_TOKEN)'